# Generated by Django 3.2.3 on 2021-06-13 14:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('subcategory_name', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('supercategory_name', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('product_desc', models.CharField(blank=True, max_length=500)),
                ('product_Smallimg', models.CharField(blank=True, max_length=100)),
                ('product_Bigimg', models.CharField(blank=True, max_length=100)),
                ('product_code', models.CharField(blank=True, max_length=100)),
                ('product_price', models.CharField(blank=True, max_length=50)),
                ('product_sell_price', models.CharField(blank=True, max_length=50)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
