# Generated by Django 3.2.3 on 2021-06-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_Bigimg',
            field=models.ImageField(upload_to='fullimages/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_Smallimg',
            field=models.ImageField(upload_to='thumb/'),
        ),
    ]
