# Generated by Django 3.2.3 on 2021-06-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210615_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_Smallimg',
            field=models.ImageField(upload_to='myupload/'),
        ),
    ]
